name: SDZ
description: A new Flutter project.
version: 1.0.0+17

environment:
  sdk: ">=2.12.0 <3.0.0"

# 依赖库
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  #=========== UI库
  # 网络图片加载插件
  cached_network_image: ^3.1.0
  # 强大的官方 Image 扩展组件, 支持加载以及失败显示，缓存网络图片，缩放拖拽图片，图片浏览(微信掘金效果)，滑动退出页面(微信掘金效果)，编辑图片(裁剪旋转翻转)，保存，绘制自定义效果等功能
  extended_image: ^4.1.0
  image_picker: ^0.8.3+3
  # 拍照图片上传裁剪
  image_cropper: ^1.4.1
  #图片预览
  photo_view: ^0.12.0
  # 吐司提示
  oktoast: ^3.1.1
  cupertino_icons: ^1.0.3
  # 下拉刷新
  flutter_easyrefresh: ^2.2.1
  #loading
  flutter_easyloading: ^3.0.3
  # 加载更多控件 A loading more list which supports ListView,GridView,WaterfallFlow and Slivers.
  loading_more_list: ^4.1.0
  # 下拉刷新组件
  pull_to_refresh_notification: ^2.2.0
  extended_nested_scroll_view: ^4.0.0
  # A collection of loading indicators animated with flutter.
  flutter_spinkit: ^5.0.0
  # 一键实现Flutter应用版本更新
  flutter_xupdate: ^2.0.1
  #验证码输入框
  pin_code_text_field: ^1.8.0
  # 瀑布流展示
  flutter_staggered_grid_view: ^0.4.0
  # 弹窗控件 https://github.com/CNAD666/flutter_smart_dialog
  flutter_smart_dialog: ^2.1.6
  # 侧滑删除
  flutter_slidable: ^0.6.0
  # 角标
  badges: ^2.0.1
  # list滚动到对应的item
  scroll_to_index:
  
  #=========== 网络相关
  dio: ^4.0.0
  dio_cookie_manager: ^2.0.0
  url_launcher: ^6.0.9
  # 访问html页面
  webview_flutter: ^2.0.12
  flutter_webview_plugin: ^0.4.0

  #flutter 选择器库
  flutter_pickers: ^2.1.1
  tcard: ^1.3.5
  flutter_swipe_action_cell: ^2.1.1
  # 文本展开收起
  expandable_text: ^2.2.0

  #=========== 存储相关
  shared_preferences: ^2.0.7
  get: ^4.3.8
  path_provider: ^2.0.2
  provider: ^6.0.0

  #=========== 工具类
  # 通知
  event_bus: ^2.0.0
  # 设备的本地化信息，比如语言，国家，地区等
  devicelocale: ^0.4.2
  cookie_jar: ^3.0.1
  # 日期格式化
  date_format: ^2.0.4
  # 权限管理
  permission_handler: 8.1.6
  # 获取软件版本号，包名，app名称等
  package_info: ^2.0.2
  # 获取当前设备信息 https://github.com/fluttercommunity/plus_plugins/tree/main/packages/device_info_plus
  device_info_plus: ^2.1.0
  # 加密工具
  crypto: ^3.0.1
  # Flutter常用工具类库 目前包含SharedPreferences Util, Screen Util, Directory Util, Widget Util, Image Util。
  flustars: ^2.0.1
  # app包信息
  package_info_plus: ^1.0.6
  # 图片保存
  gallery_saver: ^2.2.0
  #svg
  flutter_svg: ^0.22.0
  #svga
  svgaplayer_flutter: ^2.1.2
  #user-agent
  fk_user_agent: ^2.0.1
  # 处理键盘事件 https://github.com/diegoveloper/flutter_keyboard_actions
  keyboard_actions: ^3.4.4
  # 解析html文档
  flutter_html: ^2.1.1
  # lottie动画 https://pub.flutter-io.cn/packages/flutter_lottie
  lottie: ^1.1.0
  #============= 第三方
  # 微信分享 打开小程序
  fluwx: ^3.6.1+2
  #友盟
  umeng_common_sdk: ^1.2.3
  #极光推送
  jpush_flutter: 2.1.4
  share: ^2.0.4
  #腾讯优量汇广告
  flutter_qq_ads: ^2.4.1
  #闪验，一键登录
#  shanyan:
#    git:
#      url: git://github.com/253CL/CLShanYan_Flutter.git
#      path: shanyan
#      ref: v2.3.3.1

#  flutter_webview_plugin:
#    git: https://github.com/nuc134r/flutter_webview_plugin.git


  supercharged: ^2.1.1
  flutter_syntax_view: ^4.0.0
  tab_indicator_styler: ^2.0.0
  flutter_swiper_null_safety: ^1.0.2
  pull_to_refresh: ^2.0.0
  fbutton_nullsafety: ^5.0.0
  fsuper_nullsafety: ^3.0.1
#  common_utils: ^2.0.2
  extended_image_library: ^3.1.0
  waterfall_flow: ^3.0.1
  extended_list: ^3.0.0
  fsearch_nullsafety: ^2.0.0
  carousel_slider: ^4.0.0
  shimmer: ^2.0.0
  extended_text_field: ^8.0.0
  extended_text: ^7.0.0
  font_awesome_flutter: ^9.2.0
  animated_text_kit: ^4.2.1
  html: ^0.15.0
  extended_tabs: ^2.3.0
  after_layout: ^1.1.0
  palette_generator: ^0.3.2
  msix: ^2.6.3
  encrypt: ^5.0.1
  sliver_tools: ^0.2.5
  shelf: ^1.2.0
  extended_sliver: ^2.0.1
    # dd_taoke_sdk: ^1.6.1 已经弃用，换成了dataoke_sdk
#  dd_js_util:
#    git:
#      url: git://github.com/mdddj/dd_js_util
  fcontrol_nullsafety: ^2.0.0
  flutter_hooks: ^0.18.1
  hooks_riverpod: ^0.14.0+5
  get_it: ^7.2.0
  logger: ^1.1.0
  http: any
  shelf_proxy: any
  flutter_screenutil: ^5.3.1
  responsive_builder: ^0.4.1
  bubble_tab_indicator: ^0.1.6
  carousel_pro_nullsafety: ^1.0.2
  flutter_markdown: ^0.6.8
  zefyrka: ^1.0.10
  show_up_animation: ^2.0.0
  swipeable_page_route: ^0.2.4
  black_hole_flutter: ^0.3.3
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  flutter_blurhash: ^0.6.0
  #穿山甲
  flutter_pangle_ads: ^2.4.0
#  dataoke_sdk: ^0.0.1
    #  filepicker_windows: ^2.0.0  # 文件选择器
    #  win32: ^2.1.5   # windows 开放api
    #
  window_size:
    git:
      url: git://github.com/google/flutter-desktop-embedding.git  # 修改窗口标题
      path: plugins/window_size
      ref: 7812516a5c1fc8ef379e244106953a2b534432b9

#使用依赖覆盖，解决flutter版本升级之后decimal库更新导致的某些方法剔除项目运行不起来问题，，，
dependency_overrides:
  decimal: 1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  voiceread:
    path: voiceread
# 字体、图标、图片等资源加载
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/lottie/
    - assets/svg/
    - assets/nav/
    - assets/svg/cate/
    - assets/json/
    - assets/images/waimai/hb/

  fonts:
    - family: xuifont
      fonts:
        - asset: assets/fonts/iconfont.ttf